spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
