spring:
  cloud:
    gateway:
      # 配置跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许的来源
            allowedMethods: "*" #允许的请求方式
            allowedHeaders: "*" #允许所有头
            allowCredentials: true #Cookie
      # 配置网关路由
      routes:
        - id: product_route
          # 转发的服务
          uri: lb://service-product
          # 断言 匹配规则
          predicates:
            # 根据请求路径匹配
            - Path=/admin/product/**
        - id: weball_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com