spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://101.35.245.233:3306/gmall_product?useSSL=false
    username: root
    password: 131421
    driver-class-name: com.mysql.jdbc.Driver